Speakers Module Complete
ECellNitrr/EcellWeb2k19 pull request #22
Opened 2019-06-20 17:26 UTC by BadduCoder

## Speaker Module Complete with following API endpoints:
- `speakers/list/<year>`
- `speakers/generate_spreadsheet/`
- `speakers/add_new/`

2019-07-01 14:37 UTC, kdpisda requested changes
Update the PR before it is merged

2019-07-01 14:37 UTC, kdpisda commented on speakers/models.py
> +    year            = models.IntegerField(default=2019)
RIP Spacing?
Add timestamps

2019-07-01 14:37 UTC, kdpisda commented on speakers/models.py
> +        return self.name+" ("+self.company+")"
Better to format string
str("{} {}".format(self.name, self.company))

2019-07-01 14:37 UTC, kdpisda commented on frontend/package.json
> +  "name": "frontend",
Seriously @naveennvrgup ?

2019-07-01 14:37 UTC, kdpisda commented on frontend/public/index.html
> +    <title>React App</title>
React App?

2019-07-01 14:37 UTC, kdpisda commented on frontend/src/Home/about.js
> +const about=()=> (<div className="about">
Better make a react component

2019-07-01 14:37 UTC, kdpisda commented on frontend/src/Home/glimpses.js
> +import {g10} from '../Images/g10.jpeg';
Is it temporary or we are gonna use that?

2019-07-01 14:37 UTC, kdpisda commented on .gitignore
> +
@BadduCoder how many env folders?

2019-07-01 14:37 UTC, kdpisda commented on speakers/models.py
> +    year            = models.IntegerField(default=2019)
@BadduCoder ?

2019-07-08 18:36 UTC, naveennvrgup commented
closed because it not relevant.

2019-07-08 18:36 UTC, closed without merging