Startup
ECellNitrr/EcellWeb2k19 pull request #26
Opened 2019-06-24 19:53 UTC by anshsrtv

2019-06-26 14:25 UTC, ethicalrushi requested changes
Also pull the master and make sure that all checks are passed for your pr

2019-06-26 14:25 UTC, ethicalrushi commented on startup/models.py
> +
1) Make image,address an optional field
2) Use [this](https://www.python.org/dev/peps/pep-0008/#class-names) naming convention for classes

2019-06-26 14:25 UTC, ethicalrushi commented on startup/views.py
> +    startups = startup.objects.filter(year=year, verified=True)
Test this function locally

2019-06-26 14:25 UTC, ethicalrushi commented on startup/views.py
> +    startups = startup.objects.all().values_list('name', 'company', 'contact', 'email', 'experience',
Test this function locally

2019-06-26 14:25 UTC, ethicalrushi commented on startup/views.py
> +
Use validation for unique constraint to find if the entry already exists. If the entry already exists give user a message stating the same.

2019-06-27 07:51 UTC, naveennvrgup reviewed
ansh do check the working of api with postman before making a pr

2019-07-08 18:36 UTC, naveennvrgup commented
closed because it not relevant.

2019-07-08 18:36 UTC, closed without merging